---
- name: Manage repository in the list
  yum_repository:
    name: vscode
    description:  Visual Studio Code repository
    baseurl: "{{ vscode_yum_repository_url }}"
    gpgcheck: true
    gpgkey:  "{{ vscode_linux_signing_key_url }}"
    state: "{{ vscode_state }}"
  tags: vscode

- name: Make VS Code {{ vscode_state }}
  dnf:
    name: code
    state: "{{ vscode_state }}"
    update_cache: yes
  tags: vscode
