---
- name: Install Snap
  ansible.builtin.apt:
    pkg:
      - snap
      - snapd
  tags: vscode

- name: Use Snap to make VS Code {{ vscode_state }}
  community.general.snap:
    name: code
    classic: true
    state: "{{ vscode_state }}"
  tags: vscode
