---
- name: Make repository key {{ vscode_state }}
  rpm_key:
    key: "{{ vscode_linux_signing_key_url }}"
  when: vscode_state != "absent"
  tags: vscode

- name: Make repository {{ vscode_state }} in the list
  zypper_repository:
    name: vscode
    description: vscode repository
    repo: "{{ vscode_yum_repository_url }}"
    auto_import_keys: true
    state: "{{ vscode_state }}"
    runrefresh: true
  tags: vscode

- name: Make Google Chrome {{ vscode_state }}
  zypper:
    name: "google-chrome-stable"
    state: "{{ vscode_state }}"
    update_cache: true
  tags: vscode
